volumes:
  sqlserver_data:

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=my_Password
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql